apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: order-api
  name: order-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
      - image: manishkhadria/order-api:0.0.2-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: order-api
        env:
          - name: JAEGER_HOSTNAME
            value: jaeger-agent
          - name: JAEGER_PORT
            value: "6831"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: order-api
  namespace: default
  labels:
    app: order-api
spec:
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  selector:
    app: order-api
  type: ClusterIP
#  type: LoadBalancer